spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    hikari:
      pool-name: DateHikariCP
      minimum-idle: 5
      #?????????????10??
      idle-timeout: 1800000
      #????????10
      maximum-pool-size: 10
      #?????????????
      auto-commit: true
      #?????????0?????????1800000?30???
      max-lifetime: 1800000
      #?????????30000?30??
      connection-timeout: 3000
      #?????????????
      connection-test-query: SELECT 1
mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.xxxx.seckill.pojo

logging:
  level:
    com.xxxx.seckill.mapper: debug
